### ISSUE TITLE
Windows path returns backslash

### ISSUE THREAD

**Issue by WillemWubs** [atanasster/storybook-dep-webpack-plugin#1]
We run Storybook on Windows and the dep-webpack plugin throws an error on JSON parse. The reason is that in the dependencies map the paths return backslashes instead of forward slashes. To my knowledge this is expected form NodeJS path, but there is no way to change the backslash to a forward slash. It would be useful to have an option to change the separator.

https://github.com/atanasster/storybook-dep-webpack-plugin/blob/154eb0be5f183d065397a004b0afc186bd81d5c1/src/lib/index.ts#L52

**Comment by atanasster** [comment]
Thanks @WillemWubs - just ublished version 1.0.4 using path.sep for windows compatibility. Please let me know how it goes.
