### ISSUE TITLE
Thanks @WillemWubs - just published version 1.0.4 using path.sep for windows compatibility. Please let me know how it goes.

### ISSUE THREAD

**Issue by WillemWubs** [atanasster/storybook-dep-webpack-plugin#2]
Thanks for the quick reply and fix! Really appreciated. The DependenciesMap is now created correctly, it now only throws an error on JSON.parse in main.js because of the backslashes. I made a small change to line 9 in main.js and got it working. The change is : map = JSON.parse(dependenciesMap.replace(/\\/g, "/")); The backslashes are replaced by forward slashes and then the JSON is parsed correctly. Maybe you can add this change?

Thanks @WillemWubs - just published version 1.0.4 using path.sep for windows compatibility. Please let me know how it goes.

_Originally posted by @atanasster in https://github.com/atanasster/storybook-dep-webpack-plugin/issues/1#issuecomment-732422345_

**Comment by atanasster** [comment]
Thanks @WillemWubs - can you please try `1.0.5`
