### ISSUE TITLE
importing multiple named components yields only one dependency

### ISSUE THREAD

**Issue by kkckkc** [atanasster/storybook-dep-webpack-plugin#3]
When I do an import like 

```
import { ComponentA, ComponentB } from 'some-package';
```

only one of them end up as a dependency in Storybook.

I've tried to debug this, and it seems I get both dependencies if I revert https://github.com/atanasster/storybook-dep-webpack-plugin/commit/f2aee2ac4cc3a952ac811c8beeb0a81de06e0615#diff-df0a988f9e523993e537dd35bfb5768e6d1cc02349e28cceaa2e2be205433433

My conclusion is that both components ends up as two different dependencies, but they will have the same key into `asstes` array - hence only one is recorded

**Comment by atanasster** [comment]
thanks a lot for the PR, just published 1.0.6
